# Generated by Django 5.2.1 on 2025-06-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_inventoryitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_p', models.CharField(max_length=200)),
                ('email_p', models.EmailField(blank=True, max_length=254, null=True)),
                ('number_p', models.CharField(blank=True, max_length=100, null=True)),
                ('description_p', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
