# Generated by Django 5.2.1 on 2025-06-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='inventory.tag'),
        ),
    ]
