# Generated by Django 5.2.1 on 2025-06-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_tag_inventoryitem_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
    ]
