# Generated by Django 5.2.1 on 2025-06-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventoryitem_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
